src/java/View/DenunciasController.java
package View;

import DataModels.Denuncias;
import View.util.JsfUtil;
import View.util.PaginationHelper;
import ViewController.DenunciasFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("denunciasController")
@SessionScoped
public class DenunciasController implements Serializable {

    private Denuncias current;
    private DataModel items = null;
    @EJB
    private ViewController.DenunciasFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public DenunciasController() {
    }

    public Denuncias getSelected() {
        if (current == null) {
            current = new Denuncias();
            selectedItemIndex = -1;
        }
        return current;
    }

    private DenunciasFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Denuncias) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Denuncias();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DenunciasCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Denuncias) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DenunciasUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Denuncias) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DenunciasDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Denuncias getDenuncias(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Denuncias.class)
    public static class DenunciasControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DenunciasController controller = (DenunciasController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "denunciasController");
            return controller.getDenuncias(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Denuncias) {
                Denuncias o = (Denuncias) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Denuncias.class.getName());
            }
        }

    }

}

web/denuncias/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateDenunciasTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateDenunciasLabel_id}" for="id" />
                    <h:inputText id="id" value="#{denunciasController.selected.id}" title="#{bundle.CreateDenunciasTitle_id}" required="true" requiredMessage="#{bundle.CreateDenunciasRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateDenunciasLabel_titulo}" for="titulo" />
                    <h:inputText id="titulo" value="#{denunciasController.selected.titulo}" title="#{bundle.CreateDenunciasTitle_titulo}" required="true" requiredMessage="#{bundle.CreateDenunciasRequiredMessage_titulo}"/>
                    <h:outputLabel value="#{bundle.CreateDenunciasLabel_descricao}" for="descricao" />
                    <h:inputText id="descricao" value="#{denunciasController.selected.descricao}" title="#{bundle.CreateDenunciasTitle_descricao}" required="true" requiredMessage="#{bundle.CreateDenunciasRequiredMessage_descricao}"/>
                    <h:outputLabel value="#{bundle.CreateDenunciasLabel_dataDenuncia}" for="dataDenuncia" />
                    <h:inputText id="dataDenuncia" value="#{denunciasController.selected.dataDenuncia}" title="#{bundle.CreateDenunciasTitle_dataDenuncia}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateDenunciasLabel_leilao}" for="leilao" />
                    <h:selectOneMenu id="leilao" value="#{denunciasController.selected.leilao}" title="#{bundle.CreateDenunciasTitle_leilao}" required="true" requiredMessage="#{bundle.CreateDenunciasRequiredMessage_leilao}">
                        <f:selectItems value="#{leilaoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateDenunciasLabel_denunciador}" for="denunciador" />
                    <h:selectOneMenu id="denunciador" value="#{denunciasController.selected.denunciador}" title="#{bundle.CreateDenunciasTitle_denunciador}" required="true" requiredMessage="#{bundle.CreateDenunciasRequiredMessage_denunciador}">
                        <f:selectItems value="#{utilizadorController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{denunciasController.create}" value="#{bundle.CreateDenunciasSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{denunciasController.prepareList}" value="#{bundle.CreateDenunciasShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateDenunciasIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/denuncias/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditDenunciasTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditDenunciasLabel_id}" for="id" />
                    <h:inputText id="id" value="#{denunciasController.selected.id}" title="#{bundle.EditDenunciasTitle_id}" required="true" requiredMessage="#{bundle.EditDenunciasRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditDenunciasLabel_titulo}" for="titulo" />
                    <h:inputText id="titulo" value="#{denunciasController.selected.titulo}" title="#{bundle.EditDenunciasTitle_titulo}" required="true" requiredMessage="#{bundle.EditDenunciasRequiredMessage_titulo}"/>
                    <h:outputLabel value="#{bundle.EditDenunciasLabel_descricao}" for="descricao" />
                    <h:inputText id="descricao" value="#{denunciasController.selected.descricao}" title="#{bundle.EditDenunciasTitle_descricao}" required="true" requiredMessage="#{bundle.EditDenunciasRequiredMessage_descricao}"/>
                    <h:outputLabel value="#{bundle.EditDenunciasLabel_dataDenuncia}" for="dataDenuncia" />
                    <h:inputText id="dataDenuncia" value="#{denunciasController.selected.dataDenuncia}" title="#{bundle.EditDenunciasTitle_dataDenuncia}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditDenunciasLabel_leilao}" for="leilao" />
                    <h:selectOneMenu id="leilao" value="#{denunciasController.selected.leilao}" title="#{bundle.EditDenunciasTitle_leilao}" required="true" requiredMessage="#{bundle.EditDenunciasRequiredMessage_leilao}">
                        <f:selectItems value="#{leilaoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditDenunciasLabel_denunciador}" for="denunciador" />
                    <h:selectOneMenu id="denunciador" value="#{denunciasController.selected.denunciador}" title="#{bundle.EditDenunciasTitle_denunciador}" required="true" requiredMessage="#{bundle.EditDenunciasRequiredMessage_denunciador}">
                        <f:selectItems value="#{utilizadorController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{denunciasController.update}" value="#{bundle.EditDenunciasSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditDenunciasViewLink}"/>
                <br />
                <h:commandLink action="#{denunciasController.prepareList}" value="#{bundle.EditDenunciasShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditDenunciasIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/denuncias/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListDenunciasTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListDenunciasEmpty}" rendered="#{denunciasController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{denunciasController.items.rowCount > 0}">
                    <h:outputText value="#{denunciasController.pagination.pageFirstItem + 1}..#{denunciasController.pagination.pageLastItem + 1}/#{denunciasController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{denunciasController.previous}" value="#{bundle.Previous} #{denunciasController.pagination.pageSize}" rendered="#{denunciasController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{denunciasController.next}" value="#{bundle.Next} #{denunciasController.pagination.pageSize}" rendered="#{denunciasController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{denunciasController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDenunciasTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDenunciasTitle_titulo}"/>
                            </f:facet>
                            <h:outputText value="#{item.titulo}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDenunciasTitle_descricao}"/>
                            </f:facet>
                            <h:outputText value="#{item.descricao}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDenunciasTitle_dataDenuncia}"/>
                            </f:facet>
                            <h:outputText value="#{item.dataDenuncia}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDenunciasTitle_leilao}"/>
                            </f:facet>
                            <h:outputText value="#{item.leilao}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDenunciasTitle_denunciador}"/>
                            </f:facet>
                            <h:outputText value="#{item.denunciador}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{denunciasController.prepareView}" value="#{bundle.ListDenunciasViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{denunciasController.prepareEdit}" value="#{bundle.ListDenunciasEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{denunciasController.destroy}" value="#{bundle.ListDenunciasDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{denunciasController.prepareCreate}" value="#{bundle.ListDenunciasCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListDenunciasIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/denuncias/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewDenunciasTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewDenunciasLabel_id}"/>
                    <h:outputText value="#{denunciasController.selected.id}" title="#{bundle.ViewDenunciasTitle_id}"/>
                    <h:outputText value="#{bundle.ViewDenunciasLabel_titulo}"/>
                    <h:outputText value="#{denunciasController.selected.titulo}" title="#{bundle.ViewDenunciasTitle_titulo}"/>
                    <h:outputText value="#{bundle.ViewDenunciasLabel_descricao}"/>
                    <h:outputText value="#{denunciasController.selected.descricao}" title="#{bundle.ViewDenunciasTitle_descricao}"/>
                    <h:outputText value="#{bundle.ViewDenunciasLabel_dataDenuncia}"/>
                    <h:outputText value="#{denunciasController.selected.dataDenuncia}" title="#{bundle.ViewDenunciasTitle_dataDenuncia}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewDenunciasLabel_leilao}"/>
                    <h:outputText value="#{denunciasController.selected.leilao}" title="#{bundle.ViewDenunciasTitle_leilao}"/>
                    <h:outputText value="#{bundle.ViewDenunciasLabel_denunciador}"/>
                    <h:outputText value="#{denunciasController.selected.denunciador}" title="#{bundle.ViewDenunciasTitle_denunciador}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{denunciasController.destroyAndView}" value="#{bundle.ViewDenunciasDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewDenunciasEditLink}"/>
                <br />
                <h:commandLink action="#{denunciasController.prepareCreate}" value="#{bundle.ViewDenunciasCreateLink}" />
                <br />
                <h:commandLink action="#{denunciasController.prepareList}" value="#{bundle.ViewDenunciasShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewDenunciasIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>